:PROPERTIES:
:ID:       fd4dc3d5-8dab-46b4-a7cc-adb3525f058b
:END:
#+title: referral-commission
#+filetags: :asana-ticket:
* Referral Commission Not Persisting

** Asana Link
[[https://app.asana.com/0/1199696369468912/1207050891200547/f][ticket link]]

** Loom Link
[[][loom link]]

** Tasks
*** TODO submit PR
*** TODO merge PR

** Monday, April 15, 2024 Notes
i'm wondering if the ticket i'm working on should stay alive? i think a new ticket with all of this context might make more sense. will ask at stand-up.

*** Overall Summary
Wally and i are doing the right thing in supplier onboarding by setting the ~supInstantAddDesiredCommission~. however, in the inventory table the FE is being a bit too dumb. it isn't taking into account all of the logical priority that goes into determining what commission will be when a given product is ordered.

one solution for this would be adding logic on the FE to calculate actual commission and centralizing it.

another solution would be adding a field from the backend that shows what actual commission will be.

both of these have drawbacks. the first option means business logic lives on the FE and BE and needs to be updated on both if one is updated. the second option involves additional calculation that could slow things down. but at the end of the day i'm just going to assume that's the best solution available.

*** Kimia Message
=the product listing that happens after sup onboarding doesn't actually handle or reference commissions, it just updates listing status=. i'm a bit confused what product listing this is? perhaps listing all of the existing products that that supplier has or something? so i guess that means that when i update commission during onboarding it doesn't impacy any of the products that get listed.

my mutation in onboarding updates commission on ~VariantListingSksInstantlyAddableForRelationship~.

when an SK instantly adds a product the mutation that runs is ~PushInstantlyAddableProducts~. this creates the CVRLIs ([[id:39eeec9b-88be-4850-8f06-5495c82db307][acronyms]]) that are referenced to determine commission.

how commission is set when creating a product (CVRLI):
 - if an instant add commission exists via ~VariantListingSksInstantlyAddableForRelationship~ for the product, that is used
 - if ~sup_instant_add_desired_commission~ from the relationship exists, that is used
 - if ~default_supplier_commission~ exists then that is used
 - lastly default to ~supplier_desired_commission~

Kimia's understanding of the issues:
 - pre-appoval modal, scommission displayed isn't coming from ~supInstantAddDesiredCommission~ but from ~shopkeepDesiredCommission~
   - in an ideal world this field should follow same priority logic
 - sup "approved products" table does not take relationship level commission into account
   - ideally this field should match what's on the CVRLI.

ultimately it sounds like the main issues that we're seeing is the frontend prioritizing commission to show differently than the backend.

hmmm. it seems like there should be an endpoint we can hit to allow the frontend to see the result of that logic. Kimia is afraid that that will slow things down.

** Friday, April 12, 2024 Notes
*** Wally Call
 - Manage pre-approval commission rate is always set to shopkeep's desired commission
   - should it be?
   - could it just be a text element?
 - cancel on manage pre-approval modal unsets sup desired commission
   - should it?
 - manage pre-approval commission rate is set to the default commission rate
   - not the SK's desired
   - should it?

*** Summary of the Issue
when onboarding as a SUP the SK who referred you has their desired commission show up. the referred SUP can then adjust that commission number. at this point i get a bit confused. is there meant to be some sort of negotiation process here? it seems like no, the SUP gets to just set it. the issue is that after the SUP changes that commission, when an SK adds one of the SUP's products to their store they aren't seeing the adjusted commission, they're seeing the original SK's desired commission

Molly is saying that her onboarding SUP changed the commission rate. then she added a product with that SUP and the product is showing up for the SK at the SK's desired commission rate instead of the SUP onboarding requested commission. this is a bit confusing because i haven't done any automatic add stuff.

*** Reproducing/Local Testing
onboarding my SUP and setting commission to 42% (Simon SK 5's commission rate). wait wait wait. i want to be onboarded by Mickstopher Storefront.

ok fixed that by deleting the old referral object. now setting all current and future products to have that agreed commission rate.

hmm for some reason after that i'm taken to the dropshipping page? here i'm setting storefront commission to 28%.

=ok think i might finally be seeing the issue.=

*** Reproduction Steps
 - invite SUP
 - as SUP start onboarding
 - set commission rate
 - finish onboarding (make sure to set "all future products")
 - add a new product to SUP store via shopify admin
 - as SK check the product in SUP inventory
 - add to store
 - gets added with SK desired commission, not SUP designed commission

*** Code Details
i want to check out the SUP shopify shop object in the DB. it should have some reference to that commission rate that i set as the SUP.

looks like there's ~supInstantAddDesiredCommission~ in the mickstopher supplier shop object. that's nested within the relationship to storefronts area. i wonder if i delete that and re-onboard what happens.

making new commission 47%. updating that number runs ~updateShopRelationship~. does it do anything to the shop in the DB? yes! sets ~supInstantAddDesiredCommission~. so that button itself seems to work. but the issue seems to be that when a product is added to the shop it doesn't show that value. this could honestly be just because of what's displayed in the commission rate column of that table.

*** Quick Information Dump
ok so when a SUP is getting onboarded they can set ~supInstantAddDesiredCommission~. that is an item in their relationship with the SK. however, what gets displayed in the SK's Inventory table is just an amalgamation of SK commissions in the form of ~instantAddSkCommission~, ~approvedShopkeepCommission~, and ~defaultShopkeepCommission~. none of that says anything about the SUP but perhaps one of those fields gets set when the SUP sets their desired commission?

*** Invite Link
http://localhost:3000/refer_supplier?referralId=MickstopherStorefront-21efb40e3fe94978::sk

** Thursday, April 11, 2024 Notes
 - Molly called this out as blocking [[id:34eecd51-c0bd-40c5-8d58-4ce0fa69bfe5][uninstalled-inventory-table]]
 - since i made commission changeable that's likely on me
 - [[https://github.com/shopcanal/frontend/pull/5071][link to the previous PR]]
 - reproducing
   - very hard for me to reproduce entire referral process
   - might ask Molly how she's been doing that
